var GAME_LEVELS = [
  ["                                                                                   ",
   "                                                                                   ",
   "                                                                                   ",
   "                                                        xxxxx                      ",
   "                                                        x!!!x                      ",
   "      o                                                 x!!!x                      ",
   "      o                        o                        xxvxx                      ",
   "o     !               o o                                                          ",
   "x     !   o   o o                                                                  ",
   "      !                        x  o                                                ",
   "      x               xx                                               o           ",
   "  x   x   x   xxx            !!!!xx        o  o       o        o                   ",
   "  x   x                      !xxxx                                                 ",
   "  x   x!!!!!!!!!!!!!!!!!!!!!!!x                                                    ",
   "  x @ x!!!!!!!!!!!!!!!!!!!!!!!x                                        x       o  =",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx            x  x       x=       x       x!!!!!!!x!!!",
   "                                                                       xxxxxxxxxxxx",
   "                                              x!!!!!!!x                            ",
   "                                              x!!!!!!!x                            ",
   "                                              xxxxxxxxx                            ",
   "                                                                                   ",
   "                                                                                                 "],
  ["                                                                                                  ",  
   "                           xxxxx xxxx xxxx xxxx xxxx xxxx xxxx xxxx xxxxxx                        ",
   "                           x    p    p    p    p    p    p    p    p     x                        ",
   "                                                                                                  ",
   "                                  oo   oo   oo   oo   oo   oo   oo   oo                           ",
   "                                                                                o                 ",
   "                                                                                                  ",
   "       o    o    o       o                                                                        ",
   "                           xxxxx xxxx xxxx xxxx xxxx xxxx xxxx xxxx xxxxxx                        ",
   "                                                                                x                 ",
   "                                                                                                  ",
   "o      x    x    x       x                                                                        ",
   "                                x    x    x    x    x    x    x    x                              ",
   "                                o                                                          o      ",
   "x                                                                                                 ",
   "     o      oo      o       o       o        o      o                                             ",
   "                                                                                                  ",
   "                                                               o                           x      ",
   "     x      xx      x                                                                             ",
   "                            x       xx       xxxxxxxx     x                                       ",
   "                                             xxvvvvxx                                             ",
   "                                                               x       o                          ",
   "                                                                                                  ",
   "    p      p       p                                               x                              ",
   "                                                                                                  ",
   "            o       o                       o       o      o   o       x       o                  ",
   "                                                                     x                            ",  
   "      o                 o                                          x                              ",
   "                                                                 x                                ",
   "            x       x                        x!!!!!!x      xxxxxx              x                  ",
   "                                            xxxxxxxxx                                             ",
   " o    x!!!!!!!!!!!!!!!!!x     o        o   x                                                      ",
   "     x!!!!!!!!!!!!!!!!!x                  x                                                       ",
   "     xxxxxxxxxxxxxxxxxxx                 x                                                        ",
   " @                    ex                x                                                         ",
   "xxxxxxxxxxxxxxxxxxxxxxxx      x        x                                                          ",                               
   "                                                                                                  ",
   "                                                                                                  ",
   "                                                                                                  ",
   "                                                                                                  "],
  ["            p      p                                                           p       p                      ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                            o  d  o  d  o  d  o  d  o  d  o        o       o       o       o                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        x       x       x       x                  ",
   "                          xxxvvxvvxvvxvvxvvxvvxvvxvvxvvxvvx      d                                  o         ",
   "             o     o    xxx                                      x                                            ",
   "     o                                                           x                                            ",
   "                                                                 x                                            ",
   "                                                                 x                                  x         ",
   "    x        xxxxxxx                                             x                                            ",
   "    xx   o    xvvvvx                                             x         o       o       o                  ",
   "    x         x                                                  x                                            ",
   "    x         x                                                  x                                            ",
   "    x         x                                                  x                                            ",
   "    x    x    x                                                  x x       x       x       x                  ",
   "    x                                                                                               o         ",
   "    x                                                                                                         ",
   "    x                       o  o  o  o  o  o  o  o  o  o  o                                                   ",
   "    xxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx      o                                            ",
   "                             x       o                           x                                  x         ",
   "                             x                                   x                                            ",
   "                             xo                                  x         o       o       o                  ",
   "                             x                                  xx                                            ",
   "                             x       x       o          o           o                                         ",
   "                             x              xe           x                                                    ",
   "  xxxx                       xxxx          xxxxxxxxxxxxxxx                 x       x       x                  ",
   "  xvvx                          x          x                                                                  ",
   "  x                             xxxx     o x                                                                  ",
   "  x            o       o                   x                                                                  ",
   "  x                d              o        x                                                                  ",
   "  x                                        x                                                                  ",
   "  x                                      xxx                                                                  ",
   "  x            x   x   x                                                                                      ",
   "  x                       v!!!!vxxx                                 o                                         ",
   "  x                       v!!!!vx                                                                             ",
   "  xo                      v!!!!v                                                                              ",
   "  xxxx   xxxxx             xxxx                                                                               ",
   " e                                                                  @        o                                ",
   "                                                                   xx        x                                "],
  
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
